# Generated by Django 6.1.1 on 2026-10-03 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barangay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_id", models.BigIntegerField(db_index=True, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_id", models.BigIntegerField(db_index=True, null=True)),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("barangay", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "subdivision",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_id", models.BigIntegerField(db_index=True, null=True)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_id", models.BigIntegerField(db_index=True, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("prefix_type", models.CharField(blank=True, max_length=50, null=True)),
                ("suffix_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
    ]
